#!/bin/bash

folder=$1

mkdir -p $folder
cp -r docs $folder
cp -r include $folder
cp -r scripts $folder
cp -r src $folder
cp -r src_test $folder
mkdir -p $folder/tex
cp -r tex/templates $folder/tex
cp tex/commands.jinja.tex $folder/tex
cp tex/header.jinja.tex $folder/tex
cp tex/packages.jinja.tex $folder/tex
cp tex/report $folder/tex
cp tex/requirements.txt $folder/tex
cp -r toy_examples $folder
cp CMakeLists.txt $folder
cp config.yaml $folder
cp mc_mpi.sublime-project $folder
cp README.md $folder
cp test $folder
find $folder -name ".DS_Store" -type f -delete